// <auto-generated />
namespace _11_RestaurantRater.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addRatingsToRestaurant : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addRatingsToRestaurant));
        
        string IMigrationMetadata.Id
        {
            get { return "202011092108142_addRatingsToRestaurant"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
